In [1]:
!which python

/Users/tristantorchet/Desktop/Code/VSCode/LearningJAX/.venv/bin/python


# 1. Asynchronous Dispatch

In [2]:
import numpy as np
import jax.numpy as jnp
from jax import random
x = random.uniform(random.key(0), (1000, 1000))
# Printing the result (i.e. evaluating `repr(result)` or `str(result)`)
# will block until the value is ready.
jnp.dot(x, x) + 3.  

Array([[258.0197 , 249.64864, 257.13373, ..., 236.67952, 250.68939,
        241.36853],
       [265.65982, 256.28915, 262.18246, ..., 242.03183, 256.16754,
        252.44124],
       [262.38916, 255.72754, 261.2306 , ..., 240.83559, 255.41093,
        249.62468],
       ...,
       [259.1581 , 253.092  , 257.72174, ..., 242.23874, 250.72684,
        247.16638],
       [271.22662, 261.91205, 265.33398, ..., 248.26648, 262.0539 ,
        261.337  ],
       [257.16138, 254.7543 , 259.083  , ..., 241.59848, 248.62595,
        243.22354]], dtype=float32)

If you run the following cells on GPU you will see a really short Wall time (100's of us) if you don't use the blocking while a long one (10's of ms) if you use the blocking.

On CPU it doesn't matter.

In [3]:
%time jnp.dot(x, x) 

CPU times: user 47.3 ms, sys: 8.07 ms, total: 55.4 ms
Wall time: 9.76 ms


Array([[255.01973, 246.64864, 254.13373, ..., 233.67952, 247.68939,
        238.36853],
       [262.65982, 253.28915, 259.18246, ..., 239.03183, 253.16756,
        249.44124],
       [259.38916, 252.72754, 258.2306 , ..., 237.83559, 252.41093,
        246.62468],
       ...,
       [256.1581 , 250.092  , 254.72174, ..., 239.23874, 247.72684,
        244.16638],
       [268.22662, 258.91205, 262.33398, ..., 245.26648, 259.0539 ,
        258.337  ],
       [254.16138, 251.7543 , 256.083  , ..., 238.59848, 245.62595,
        240.22354]], dtype=float32)

In [4]:
%time np.asarray(jnp.dot(x, x))  

CPU times: user 46.1 ms, sys: 2.5 ms, total: 48.6 ms
Wall time: 7.14 ms


array([[255.01973, 246.64864, 254.13373, ..., 233.67952, 247.68939,
        238.36853],
       [262.65982, 253.28915, 259.18246, ..., 239.03183, 253.16756,
        249.44124],
       [259.38916, 252.72754, 258.2306 , ..., 237.83559, 252.41093,
        246.62468],
       ...,
       [256.1581 , 250.092  , 254.72174, ..., 239.23874, 247.72684,
        244.16638],
       [268.22662, 258.91205, 262.33398, ..., 245.26648, 259.0539 ,
        258.337  ],
       [254.16138, 251.7543 , 256.083  , ..., 238.59848, 245.62595,
        240.22354]], dtype=float32)

In [5]:
%time jnp.dot(x, x).block_until_ready()

CPU times: user 48.6 ms, sys: 6.96 ms, total: 55.5 ms
Wall time: 8.31 ms


Array([[255.01973, 246.64864, 254.13373, ..., 233.67952, 247.68939,
        238.36853],
       [262.65982, 253.28915, 259.18246, ..., 239.03183, 253.16756,
        249.44124],
       [259.38916, 252.72754, 258.2306 , ..., 237.83559, 252.41093,
        246.62468],
       ...,
       [256.1581 , 250.092  , 254.72174, ..., 239.23874, 247.72684,
        244.16638],
       [268.22662, 258.91205, 262.33398, ..., 245.26648, 259.0539 ,
        258.337  ],
       [254.16138, 251.7543 , 256.083  , ..., 238.59848, 245.62595,
        240.22354]], dtype=float32)